### ISSUE TITLE
Header Alignment Issue

### ISSUE THREAD

**Issue by mcclede** [laertejjunior/freezeheader#23]
I use a style of "margin: auto" to cause my table to be centered in the viewport. However, the frozen header remains left aligned.
Any suggestions on how to fix this, or do it better?

![Header Alignment Issue](https://user-images.githubusercontent.com/91996647/154373582-4eb4e099-c92e-4ffb-851c-dcbb9f33acc0.png)

You can also see it live at https://www.socalofficials.org/index.html?api/activeMemberStatus

**Comment by laertejjunior** [comment]
Hey, friend. I've been involved in other projects and only got to see it today. Did you solve it or are you still having trouble?
I can't open the https://www.socalofficials.org/index.html?api/activeMemberStatus.
Sorry for only replying now...

**Comment by mcclede** [comment]
Thanks for getting back to me. Yes, I'm still having the problem. The link
I sent you seems to work for me, but you can try
https://www.socalofficials.org, then click on the "Verify your meeting
attendance and dues status" link. As you scroll down, you'll see what I
mean.
The table with the header is centered using "margin: auto", but the frozen
header does not seem to inherit this. Not sure what to do about it.

**Comment by laertejjunior** [comment]
Hi, i published a new version in a development branch with some changes.

[https://github.com/laertejjunior/freezeheader/blob/feature/on-center/js/jquery.freezeheader.js](url)

`
$("#rosterTable").freezeHeader({
    onCenter: true
});
`

**Comment by mcclede** [comment]
Thanks! That works great for me.

**Comment by laertejjunior** [comment]
I saw that you are using Symfony in your project. In the .env file, I think you missed setting the APP_ENV=prod for the toolbar to stop appearing.

**Comment by mcclede** [comment]
Thanks. Yes, I’m not quite ready to put it into production yet. From: Laerte Mercier JuniorSent: Friday, March 25, 2022 3:56 PMTo: laertejjunior/freezeheaderCc: mcclede; AuthorSubject: Re: [laertejjunior/freezeheader] Header Alignment Issue (Issue #23) I saw that you are using Symfony in your project. In the .env file, I think you missed setting the APP_ENV=prod for the toolbar to stop appearing.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
